### ISSUE TITLE
missing 3d designs for cups and waterlevel

### ISSUE THREAD

**Issue by Candymirror** [MakeMagazinDE/Hydrokultur#1]
I bought the dutch version of this issue (make 4/2021). It refers to make-magazin.de/xj99 but there is nothing to be found. From de german article I found this github page and axpected to find the 3d printables.

**Comment by MakeMagazinDE** [comment]
Hi Candymirror,

make-magazin.de/xj99 is a redirect to https://www.heise.de/select/make/2021/1/softlinks/xj99 
There you'll find the link to https://www.thingiverse.com/thing:4735763 and the printables.

All the best
Helga/hch
